name : deploy to kebsas airflow
on :
  push:
    branches: 
      - master
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secret.SSH_HOST }}
          user: ${{ secret.SSH_USERNAME }}
          key: ${{ secret.SSH_KEY }}
          command: cd /airflow/dags/ && git pull origin master && chown airflow:airflow /airflow/dags/